// CHARACTERS
export const GET_ALL_CHARACTERS_PENDING = 'GET_ALL_CHARACTERS_PENDING';
export const GET_ALL_CHARACTERS_SUCCESS = 'GET_ALL_CHARACTERS_SUCCESS';
export const GET_ALL_CHARACTERS_ERROR = 'GET_ALL_CHARACTERS_ERROR';
export const UPDATE_CHARACTERS_PENDING = 'UPDATE_CHARACTERS_PENDING';
export const UPDATE_CHARACTERS_SUCCESS = 'UPDATE_CHARACTERS_SUCCESS';
export const UPDATE_CHARACTERS_ERROR = 'UPDATE_CHARACTERS_ERROR';
export const UPDATE_CHARACTERS_PARAMS = 'UPDATE_CHARACTERS_PARAMS';


// LOCATIONS
export const GET_ALL_LOCATIONS_PENDING = 'GET_ALL_LOCATIONS_PENDING';
export const GET_ALL_LOCATIONS_SUCCESS = 'GET_ALL_LOCATIONS_SUCCESS';
export const GET_ALL_LOCATIONS_ERROR = 'GET_ALL_LOCATIONS_ERROR';
export const UPDATE_LOCATIONS_PENDING = 'UPDATE_LOCATIONS_PENDING';
export const UPDATE_LOCATIONS_SUCCESS = 'UPDATE_LOCATIONS_SUCCESS';
export const UPDATE_LOCATIONS_ERROR = 'UPDATE_LOCATIONS_ERROR';
export const UPDATE_LOCATIONS_PARAMS = 'UPDATE_LOCATIONS_PARAMS';


// EPISODES
export const GET_ALL_EPISODES_PENDING = 'GET_ALL_EPISODES_PENDING';
export const GET_ALL_EPISODES_SUCCESS = 'GET_ALL_EPISODES_SUCCESS';
export const GET_ALL_EPISODES_ERROR = 'GET_ALL_EPISODES_ERROR';
export const UPDATE_EPISODES_PENDING = 'UPDATE_EPISODES_PENDING';
export const UPDATE_EPISODES_SUCCESS = 'UPDATE_EPISODES_SUCCESS';
export const UPDATE_EPISODES_ERROR = 'UPDATE_EPISODES_ERROR';
export const UPDATE_EPISODES_PARAMS = 'UPDATE_EPISODES_PARAMS';

